collections:
  capsules:
    output: true
  references:
    output: true
exclude: ["README.md", "Gemfile", "Gemfile.lock"]
defaults:
  - scope:
      path: ""
      type: "capsules"
    values:
      layout: "capsule"
  - scope:
      path: ""
    values:
      layout: "default"
url: danielarmengolaltayo.github.io
baseurl: /hyperlink